### ISSUE TITLE
Really low minimum voltage

### ISSUE THREAD

**Issue by WereCatf** [xtacocorex/chip_batt_autoshutdown#1]
Li-ion and lipo batteries should not be discharged to below ~3.0V under load or you'll damage them permanently, getting less and less out of them each time. It would be a good idea to adjust the minimum voltage, in case someone decides to use your script.

**Comment by xtacocorex** [comment]
Yeah, when I uploaded it I wasn't sure of the voltage, when I get back near my computer I'll update.

**Comment by xtacocorex** [comment]
Updated to 3100mV.  You good with this change @WereCatf?  If so, I'll go ahead and close it.

**Comment by WereCatf** [comment]
Och, aye. Why not a nice, round 3000? Oh well, I'm not going to pick on you about that. I just figured having a safe default, in case some beginner used your script, was for the best. Letting the battery go too low can even cause a lithium-fire, just as overcharging can, and you sure don't want beginners having none of that.
